### ISSUE TITLE
[Enhancement] Add a link to Edit this page

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/DocsApp#33]
### Summary
Add a link to Edit this page
![Getting Started 2019-04-02 13-10-45](https://user-images.githubusercontent.com/2138260/55382958-c99c9800-5548-11e9-98a1-25d4606ce62e.png)

Example: https://cube.dev/docs/getting-started

### Why is it needed?
For convenience, go to the documentation page on

### Related issue(s)/PR(s)
NA

**Comment by Mark-H** [comment]
We already have that :) The "Improve the documentation" link under the title goes directly to editing the page on github.

In #30 Chris also added the same to the edit link in the footer (which previously only linked to the root of the repo) and updated both links to go to modxorg/Docs instead of Mark-H/Docs.
