### ISSUE TITLE
Top menu in the Russian version does not include one line.

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/DocsApp#38]
## Summary

The menu in the Russian version does not include one line.

**English:**

https://docs.modx.org/current/en/index

![1](https://user-images.githubusercontent.com/2138260/55929155-4280ab80-5c3d-11e9-819f-55886493fa6d.png)

**Russian:**

https://docs.modx.org/current/ru/index

![Index | MODX Documentation 2019-04-11 09-34-36](https://user-images.githubusercontent.com/2138260/55929158-46143280-5c3d-11e9-9afd-39455d5f6e35.png)

My suggestion is to move the top menu to the left block. 
And where previously there was a menu to locate the search, and the place where previously the search was planned to use under the links with the icons of GitHub, Twitter, Slack.

**Example**:
![Tailwind CSS - A Utility-First CSS Framework for Rapid UI Development 2019-04-11 09-52-41](https://user-images.githubusercontent.com/2138260/55929678-91c7db80-5c3f-11e9-924d-1c5332f3588a.png)

**Comment by Mark-H** [comment]
I'd love to hear from others with more design skill about this. 

My thoughts are that I'm not yet sure how the menu would function when the sections (Getting Started, Building Sites, etc) are also part of the sidenav. Would the sidenav contain basically the entire sitemap (which is 500+ pages) and If someone wanted to go to Extras, would they need to scroll all the way to the bottom? Or would it be some sort of selector at the top to switch sections? 

While the Tailwind docs are awesome, they are also _much_ simpler with only a few dozen instead of a few hundred pages, so we can't just copy/paste from them. 

I do like the idea of making the search more prominent and am planning to work on making that functional in the next week or two.

**Comment by Mark-H** [comment]
The concept from this tweet could work: https://twitter.com/adamwathan/status/1114552470745669632?s=19

**Comment by christianseel** [comment]
I'd say solved with the new design? Agree @Ibochkarev ?

**Comment by Ibochkarev** [comment]
@christianseel Solved. Thanks!
