### ISSUE TITLE
Issue on extras/collections

### ISSUE THREAD

**Issue by Ibochkarev** [modxorg/DocsApp#68]
## Affected page(s)

https://docs.modx.com/current/en/extras/collections

## What needs to be improved?

Broken images

![image](https://user-images.githubusercontent.com/2138260/70861207-e5b85c00-1f54-11ea-9986-28ce6c39e425.png)

**Comment by Mark-H** [comment]
While it's fixed in the app, .com is running a different server configuration that's bypassing the app handling of the doc-specific images (served from outside of the webroot by Views\Doc) causing all images to 404. Tried to fix that, but then .com went down completely so that's now temporarily redirecting to .org again.

**Comment by Mark-H** [comment]
Has been fixed for a while.
